<a href="https://colab.research.google.com/github/JoseSergio414/Fontes_dados/blob/main/PROJETOII.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Cadeia Automotiva

In [1]:
import pandas as pd

In [2]:
from google.colab import drive

In [3]:
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
origem = '/content/drive/MyDrive/Data/COMEXSTAT/'

In [7]:
arquivo_1 = origem + 'EXP_2021_MUN.csv'
arquivo_2 = origem + 'EXP_2022_MUN.csv'
arquivo_3 = origem + 'EXP_2023_MUN.csv'
arquivo_4 = origem + 'EXP_2024_MUN.csv'
arquivo_4 = origem + 'EXP_2025_MUN.csv'
arquivo_5 = origem + 'EXP_2026_MUN.csv'
ncm = origem + 'NCM.csv'
pais = origem + 'PAIS.csv'
urf = origem + 'URF.csv'
uf_mun =origem + 'UF_MUN.csv'
ncm_unidade = origem +'NCM_UNIDADE.csv'
ncm_sh = origem + 'NCM_SH.csv'
ncm_cgce = origem + 'NCM_CGCE.csv'
via = origem + 'VIA.csv'

In [8]:
exp21 = pd.read_csv(arquivo_1,low_memory=False,sep=';',encoding='UTF-8')
exp22 = pd.read_csv(arquivo_2,low_memory=False,sep=';',encoding='UTF-8')
exp23 = pd.read_csv(arquivo_1,low_memory=False,sep=';',encoding='UTF-8')
exp24 = pd.read_csv(arquivo_1,low_memory=False,sep=';',encoding='UTF-8')
exp25 = pd.read_csv(arquivo_2,low_memory=False,sep=';',encoding='UTF-8')
exp26 = pd.read_csv(arquivo_2,low_memory=False,sep=';',encoding='UTF-8')
expncm = pd.read_csv(ncm,low_memory=False,sep=';',encoding='latin1')
exppais = pd.read_csv(pais,low_memory=False,sep=';',encoding='latin1')
expurf = pd.read_csv(urf,low_memory=False,sep=';',encoding='latin1')
expufmun = pd.read_csv(uf_mun,low_memory=False,sep=';',encoding='latin1')
expunid = pd.read_csv(ncm_unidade,low_memory=False,sep=';',encoding='latin1')
expsh = pd.read_csv(ncm_sh,low_memory=False,sep=';',encoding='latin1')
expcgce = pd.read_csv(ncm_cgce,low_memory=False,sep=';',encoding='latin1')
expvia = pd.read_csv(via,low_memory=False,sep=';',encoding='latin1')

In [9]:
exp25.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1087131 entries, 0 to 1087130
Data columns (total 8 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   CO_ANO      1087131 non-null  int64
 1   CO_MES      1087131 non-null  int64
 2   SH4         1087131 non-null  int64
 3   CO_PAIS     1087131 non-null  int64
 4   SG_UF_MUN   1087131 non-null  object
 5   CO_MUN      1087131 non-null  int64
 6   KG_LIQUIDO  1087131 non-null  int64
 7   VL_FOB      1087131 non-null  int64
dtypes: int64(7), object(1)
memory usage: 66.4+ MB

In [10]:
exp25.info(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1087131 entries, 0 to 1087130
Data columns (total 8 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   CO_ANO      1087131 non-null  int64
 1   CO_MES      1087131 non-null  int64
 2   SH4         1087131 non-null  int64
 3   CO_PAIS     1087131 non-null  int64
 4   SG_UF_MUN   1087131 non-null  object
 5   CO_MUN      1087131 non-null  int64
 6   KG_LIQUIDO  1087131 non-null  int64
 7   VL_FOB      1087131 non-null  int64
dtypes: int64(7), object(1)
memory usage: 66.4+ MB

In [11]:
expncm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13742 entries, 0 to 13741
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CO_NCM          13742 non-null  int64
 1   CO_UNID         13742 non-null  int64
 2   CO_SH6          13742 non-null  int64
 3   CO_PPE          13436 non-null  float64
 4   CO_PPI          13436 non-null  float64
 5   CO_FAT_AGREG    13720 non-null  float64
 6   CO_CUCI_ITEM    13742 non-null  object
 7   CO_CGCE_N3      13742 non-null  int64
 8   CO_SIIT         13436 non-null  float64
 9   CO_ISIC_CLASSE  13742 non-null  int64
 10  CO_EXP_SUBSET   13434 non-null  float64
 11  NO_NCM_POR      13742 non-null  object
 12  NO_NCM_ESP      13742 non-null  object
 13  NO_NCM_ING      13742 non-null  object
dtypes: float64(5), int64(5), object(4)
memory usage: 1.5+ MB

In [12]:
exp_final = pd.concat([exp21,exp22,exp23,exp24,exp25,exp26], ignore_index=True)

In [13]:
exp_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6487959 entries, 0 to 6487958
Data columns (total 8 columns):
 #   Column      Dtype
---  ------      -----
 0   CO_ANO      int64
 1   CO_MES      int64
 2   SH4         int64
 3   CO_PAIS     int64
 4   SG_UF_MUN   object
 5   CO_MUN      int64
 6   KG_LIQUIDO  int64
 7   VL_FOB      int64
dtypes: int64(7), object(1)
memory usage: 396.0+ MB

In [14]:
exp_final.head(5)

   CO_ANO  CO_MES   SH4  CO_PAIS SG_UF_MUN   CO_MUN  KG_LIQUIDO  VL_FOB
0    2021       3  3305      493        SP  3434401         966    7788
1    2021       7  8419      386        SP  3409502           1    1544
2    2021      12  8511       63        PR  4106902          73     907
3    2021       7  6204      586        SC  4202909          75    3942
4    2021       8  8708       63        SP  3440002        6949   29604

In [15]:
exp_final.tail(5)

         CO_ANO  CO_MES   SH4  CO_PAIS SG_UF_MUN   CO_MUN  KG_LIQUIDO  VL_FOB
6487954    2022       9  2201      445        SP  3448500        1260     328
6487955    2022       7  9603      586        RS  4304804          24     350
6487956    2022       9  8527      239        PR  4120804         234   34731
6487957    2022       1   203      767        PA  1506807          30     226
6487958    2022       1  8527       63        SP  3452403           7    2246

In [17]:
exp_final_merged = pd.merge(exp_final, exppais[['CO_PAIS', 'NO_PAIS']], on='CO_PAIS', how='left')
coluna = 'NO_PAIS'
cp = exp_final_merged[coluna].value_counts().sort_values(ascending=False)
print(f'total de operações {coluna}:')
print(cp)

total de operações NO_PAIS:
NO_PAIS
Estados Unidos                             447981
Paraguai                                   434166
Argentina                                  416739
Uruguai                                    307881
Chile                                      299184
                                            ...
Saara Ocidental                                 3
Geórgia do Sul e Sandwich do Sul, Ilhas         3
Território Britânico do Oceano Índico           3
Santa Helena                                    3
Groenlândia                                     3
Name: count, Length: 247, dtype: int64

In [18]:
print(exp_final.columns)

Index(['CO_ANO', 'CO_MES', 'SH4', 'CO_PAIS', 'SG_UF_MUN', 'CO_MUN',
       'KG_LIQUIDO', 'VL_FOB'],
      dtype='object')

In [19]:
exp_final.to_csv(origem+'exp_final.csv',index=False)